import Link from "next/link";
import { ArrowLeft } from "lucide-react";

interface LegalDocProps {
  title: string;
  lastUpdated: string;
  legalEmail: string;
  children: React.ReactNode;
}

export function LegalDoc({ title, lastUpdated, legalEmail, children }: LegalDocProps) {
  return (
    <section className="max-w-3xl mx-auto px-4 md:px-8 py-16 md:py-20">
      <Link
        href="/legal"
        className="inline-flex items-center gap-1.5 text-xs font-medium text-white/50 hover:text-white transition-colors mb-8"
      >
        <ArrowLeft className="h-3.5 w-3.5" />
        Back to Legal
      </Link>

      <header className="mb-10">
        <p className="text-xs font-mono uppercase tracking-widest text-rose-300">
          Legal
        </p>
        <h1 className="mt-3 text-3xl md:text-4xl font-semibold tracking-tight text-white leading-tight">
          {title}
        </h1>
        <p className="mt-3 text-sm text-white/55">
          Last updated: {lastUpdated} &middot; Contact:{" "}
          <a href={`mailto:${legalEmail}`} className="hover:text-white underline">
            {legalEmail}
          </a>
        </p>
      </header>

      <article className="max-w-none text-white/75 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:tracking-tight [&_h2]:text-white [&_h2]:mt-10 [&_h2]:mb-3 [&_h3]:text-base [&_h3]:font-semibold [&_h3]:text-white [&_h3]:mt-6 [&_h3]:mb-2 [&_p]:text-sm [&_p]:leading-relaxed [&_p]:mt-3 [&_ul]:text-sm [&_ul]:leading-relaxed [&_ul]:mt-3 [&_ul]:list-disc [&_ul]:pl-5 [&_li]:mt-1 [&_a]:text-white [&_a]:underline [&_strong]:text-white">
        {children}
      </article>

      <footer className="mt-16 pt-6 border-t border-white/10 text-xs text-white/55 space-y-2">
        <p className="font-mono uppercase tracking-widest text-white/40">
          Notice
        </p>
        <p>
          This document was generated by an automated agent based on provided company information.
          It has not been reviewed by a licensed attorney.
        </p>
        <p className="font-semibold text-white/80">
          [LEGAL REVIEW REQUIRED BEFORE PUBLISHING]
        </p>
      </footer>
    </section>
  );
}
